### ISSUE TITLE
How to use libsml in ESPhome?

### ISSUE THREAD

**Issue by Qhilm** [volkszaehler/libsml#146]
Even though ESPhome now has [SML support](# https://github.com/esphome/esphome-docs/blob/current/components/sml.rst), it does not have a specific [workaround](https://github.com/volkszaehler/libsml/pull/136) I need for my WS7412.1.

Hence my question: can I replace this ESPhome yaml (for the ESPHome built-in SML support):

```yaml
external_components:
  - source:
      type: local
      path: components
    components: [ sml ]
```

with

```yaml
external_components:
  - source:
      type: git
      url: https://github.com/volkszaehler/libsml
    components: [ sml ]
 ```
 
 as a drop in replacement? Or is it more complex than this?
 
I intend to test this, but I wanted to hear if someone can say I am completely on the wrong track here and it will not work at all like that, I can try to reproduce the workaround either in ESPhome or Home Assistant yaml while using the built-in SML support from ESPHome.

This would be with ESPhome 2023.12.9 and Home Assistant 2024.01.1.
